name: Notify the Gchat Group for PRs from forks
on:
  pull_request_target:
    types: [opened]
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
    - name: Google Chat Notification
      if: ${{ github.event.pull_request.head.repo.full_name != '1-Platform/op-components' }}
      uses: gautamkrishnar/google-chat-notification@master
      with:
        url: ${{ secrets.GOOGLE_CHAT_WEBHOOK }}
