name: Storybook deployment
on: 
  push:
    branches: 
      - 'master'
jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12.x'
      - name: Setup node
        run: 'npm i && npm run build:packages'
        env: 
          CI: true
      - name: Build
      - run: npm run build-storybook
      - name: Deploy
        if: success()
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with: 
          ACCESS_TOKEN: ${{ secrets.GH_STORYBOOK_DEPLOYMENT }}
          BRANCH: gh-pages
          FOLDER: storybook-static
