name: Storybook deployment
on: 
  workflow_dispatch:
  push:
    branches: 
      - master
jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        env:
          NODE_ENV: development
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - run: npm install 
      - run: npm run build:packages 
      - name: Run headless test
        uses: GabrielBB/xvfb-action@v1
        with:
          run: npm run test:packages 
      - name: Build Storybook
        run: npm run build-storybook 
      - name: Deploy Storybook
        if: success()
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with: 
          ACCESS_TOKEN: ${{ secrets.GH_STORYBOOK_DEPLOYMENT }}
          BRANCH: gh-pages
          FOLDER: storybook-static
