name: Storybook deployment
on: 
  workflow_dispatch:
  push:
    branches: 
      - master
jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - name: Setup node
        run: npm i
        env: 
          CI: true
          name: Test and build all packages
          run: |
           npm test
           npm run build:packages
      - name: Build Storybook
        run: npm run build-storybook
      - name: Deploy Storybook
        if: success()
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with: 
          ACCESS_TOKEN: ${{ secrets.GH_STORYBOOK_DEPLOYMENT }}
          BRANCH: gh-pages
          FOLDER: storybook-static
